// <auto-generated />
using DaggerheartProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaggerheartProject.Migrations
{
    [DbContext(typeof(DaggerheartContext))]
    [Migration("20261004225557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaggerheartProject.Models.DaggerheartCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Evasion")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("DaggerheartCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "Warrior",
                            Evasion = 11,
                            HitPoints = 6,
                            Name = "Chug Fligadoo"
                        },
                        new
                        {
                            Id = 2,
                            Class = "Druid",
                            Evasion = 10,
                            HitPoints = 6,
                            Name = "Norman Chesnut"
                        },
                        new
                        {
                            Id = 3,
                            Class = "Wizard",
                            Evasion = 11,
                            HitPoints = 5,
                            Name = "Ena"
                        },
                        new
                        {
                            Id = 4,
                            Class = "Rogue",
                            Evasion = 12,
                            HitPoints = 6,
                            Name = "Rusty Peters"
                        },
                        new
                        {
                            Id = 5,
                            Class = "Seraph",
                            Evasion = 9,
                            HitPoints = 7,
                            Name = "Jebadiah Jemsen"
                        },
                        new
                        {
                            Id = 6,
                            Class = "Guardian",
                            Evasion = 9,
                            HitPoints = 7,
                            Name = "Charles Limburger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
